#!/data/data/com.termux/files/usr/bin/bash

## termux-style installer script

## ANSI Colors (FG & BG)
RED="$(printf '\033[31m')"  GREEN="$(printf '\033[32m')"  ORANGE="$(printf '\033[33m')"  BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"  CYAN="$(printf '\033[36m')"  WHITE="$(printf '\033[37m')" BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')"  GREENBG="$(printf '\033[42m')"  ORANGEBG="$(printf '\033[43m')"  BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')"  CYANBG="$(printf '\033[46m')"  WHITEBG="$(printf '\033[47m')" BLACKBG="$(printf '\033[40m')"
DEFAULT_FG="$(printf '\033[39m')"  DEFAULT_BG="$(printf '\033[49m')"

## Directories
TERMUX_DIR="$HOME/.termux"
DIR="$(pwd)"

## Banner
banner () {
    clear
    echo "
    ${BLUE}┌──────────────────────────────────────────────────┐
    ${BLUE}│${RED}░▀█▀░█▀▀░█▀▄░█▄█░█░█░█░█${ORANGE}░░░░░${GREEN}█▀▀░▀█▀░█░█░█░░░█▀▀░░${BLUE}│
    ${BLUE}│${RED}░░█░░█▀▀░█▀▄░█░█░█░█░▄▀▄${ORANGE}░▄▄▄${RED}░${GREEN}▀▀█░░█░░░█░░█░░░█▀▀░░${BLUE}│
    ${BLUE}│${RED}░░▀░░▀▀▀░▀░▀░▀░▀░▀▀▀░▀░▀${ORANGE}░░░░░${GREEN}▀▀▀░░▀░░░▀░░▀▀▀░▀▀▀░░${BLUE}│
    ${BLUE}└──────────────────────────────────────────────────┘
    ${BLUE}"
}

## Script Termination
exit_on_signal_SIGINT () {
    { printf "\n\n%s\n" "    ${BLUE}[${RED}*${BLUE}] ${RED}Script interrupted." 2>&1; echo; reset_color; }
    exit 0
}

exit_on_signal_SIGTERM () {
    { printf "\n\n%s\n" "    ${BLUE}[${RED}*${BLUE}] ${RED}Script terminated." 2>&1; echo; reset_color; }
    exit 0
}

trap exit_on_signal_SIGINT SIGINT
trap exit_on_signal_SIGTERM SIGTERM

## Reset terminal colors
reset_color() {
	tput sgr0   # reset attributes
	tput op     # reset color
    return
}

## Prerequisite
prerequisite() {
	{ echo; echo "    ${BLUE}[${RED}*${BLUE}] ${ORANGE}Installing Dependencies..."${CYAN}; echo; }
	if [[ (-f $PREFIX/bin/curl) && (-f $PREFIX/bin/wget) && (-f $PREFIX/bin/tput) ]]; then
		{ echo "    ${BLUE}[${RED}*${BLUE}] ${GREEN}Dependencies are already Installed!"; }
	else
		{ pkg install -y curl wget ncurses-utils; }
		(type -p curl wget tput &> /dev/null) && { echo; echo "    ${BLUE}[${RED}*${BLUE}] ${GREEN}Dependencies are succesfully installed!"; } || { echo; echo "    ${BLUE}[${RED}!${BLUE}] ${RED}Error Occured, failed to install dependencies."; echo; reset_color; exit 1; }
	fi
}

## Install termux-style
install_style () {
	echo "    ${BLUE}[${RED}*${BLUE}] ${ORANGE}Installing termux-style..."
	# Delete old files
	if [[ (-L $PREFIX/bin/style) && (-d $TERMUX_DIR/colors) && (-d $TERMUX_DIR/fonts) ]]; then
	    echo "    ${BLUE}[${RED}*${BLUE}] ${RED}Deleting files from previous installation..."${BLUE}
		{ rm -rf $PREFIX/bin/style $TERMUX_DIR/colors TERMUX_DIR/fonts; echo; }
	fi
	# Copying files
	{ echo "    ${BLUE}[${RED}*${BLUE}] ${ORANGE}Copying files in ${GREEN}$PREFIX/share ${ORANGE}directory..."${BLUE}; }
	{ mkdir $TERMUX_DIR/colors; mkdir $TERMUX_DIR/fonts; cp -r $DIR/colors $TERMUX_DIR/colors; cp -r $DIR/fonts $TERMUX_DIR/fonts; cp -r $DIR/style $PREFIX/bin; }
	{ chmod +x $PREFIX/bin/style; }
	# Verify files 
	if [[ (-L $PREFIX/bin/style) && (-d $TERMUX_DIR/colors) && (-d $TERMUX_DIR/fonts) ]]; then
		{ echo; echo "    ${BLUE}[${RED}*${BLUE}] ${GREEN}Successfully Installed."; }
		{ echo "    ${BLUE}[${RED}*${BLUE}] ${GREEN}Now you can Run this Program by just typing ${MAGENTA}style${GREEN}."; echo; }
		{ reset_color; exit 0; }
	else
		{ echo "    ${BLUE}[${RED}!${BLUE}] ${RED}Error Occured."; echo; reset_color; exit 1; }
	fi
}

## Main
main () {
	banner
	prerequisite
	# Check for previous installation
	if [[ (-L $PREFIX/bin/style) && (-d $TERMUX_DIR/colors) && (-d $TERMUX_DIR/fonts) ]]; then
		{ echo; echo "    ${BLUE}[${RED}!${BLUE}] ${MAGENTA}termux-style ${GREEN}is already installed."; }
		{ read -p "    ${BLUE}[${RED}?${BLUE}] ${ORANGE}Do you wanna re-install it? (y/n): ${GREEN}"; echo; }
		if [[ "$REPLY" =~ ^[y/Y]$ ]]; then
			install_style
		else
			{ reset_color; exit; }
		fi
	else
		{ echo; install_style; }
	fi
}

main
